### ISSUE TITLE
Quick reload on continuous listening panel

### ISSUE THREAD

**Issue by jbwharris** [nrubin29/finale#9]
One thing I notice I end up doing is leaving the continuous listening panel and then back into it often. Sometimes Finale will stop scrobbling and I'll have to reinitiate the continuous listening. I'm wondering if a quick reload button would solve that problem for me. 

Related, but would be a different feature that I'm not sure if this is possible, but I'd love some type of visual indicator that it's been X minutes since the last scrobble. So I can visually see that it's probably stopped scrobbling.

**Comment by nrubin29** [comment]
Currently, the continuous scrobbler only scrobbles while you're on that screen, so if you go back and browse elsewhere in the app, it'll stop listening. I could rework it so that you can browse the app and still have it recognize in the "background".

Unfortunately, due to iOS limitations, the app has to be active in order for it to use the microphone (so it's impossible for it to continue listening if the phone is locked or you switch to another app -- I believe this is true, but I'll double check). Would this be useful to you?

**Comment by jbwharris** [comment]
My goal with this was less about navigating the app, it was about reinitiating the continuous listening session.

- Sometimes it freezes after scrobbling for awhile and just needs a fresh session
- I want to catch the end of a song on radio, but the app isn't listening right at that second. Being able to quick refresh to catch that song would be handy.

**Comment by nrubin29** [comment]
This feature has been implemented, so I'm going to go ahead and close this issue. Feel free to reopen if needed.
